
server:
  port: 3333

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:platform_security
    username: root
    password: root

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: INFO
